# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/Components/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  SubtaskButton: require './SubtaskButton'
  Task:          require './Task'         