# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/Components/Pages/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Home:           require './Home'          
  StandardImport: require './StandardImport'