# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/Components/Pages/namespace.coffee

module.exports = (require '../namespace').addNamespace('Pages', class Pages extends Neptune.PackageNamespace)
