# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  AppPalette:     require './AppPalette'    
  Main:           require './Main'          
  StandardImport: require './StandardImport'
require './Components'
require './Models'