# generated by Neptune Namespaces v3.x.x
# file: tests/Focus.App/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Focus.App', class App extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
