# generated by Neptune Namespaces v3.x.x
# file: Focus.App/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Focus.App', class App extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Client/namespace'