# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Task:         require './Task'        
  TaskNavState: require './TaskNavState'
  ViewState:    require './ViewState'   