# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App: require './App'
require './Pages'
require './Partials'
require './Widgets'