# generated by Neptune Namespaces v3.x.x
# file: Focus.App/Client/Components/Partials/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  StandardImport: require './StandardImport'
  Subtasks:       require './Subtasks'      
  Task:           require './Task'          
  Task2:          require './Task2'         